// Code generated by "stringer -type=ErrVersion"; DO NOT EDIT.

package version

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrNoVersion-0]
	_ = x[ErrNoVersionFile-1]
	_ = x[ErrOpenVersionFile-2]
}

const _ErrVersion_name = "ErrNoVersionErrNoVersionFileErrOpenVersionFile"

var _ErrVersion_index = [...]uint8{0, 12, 28, 46}

func (i ErrVersion) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ErrVersion_index)-1 {
		return "ErrVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrVersion_name[_ErrVersion_index[idx]:_ErrVersion_index[idx+1]]
}
