// Code generated by "stringer -type=Error"; DO NOT EDIT.

package repo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrThemes-0]
	_ = x[ErrActors-1]
	_ = x[ErrLockActor-2]
	_ = x[ErrUnlockActor-3]
	_ = x[ErrIsActorLocked-4]
	_ = x[ErrResetActorLocks-5]
	_ = x[ErrStartSession-6]
	_ = x[ErrStopSession-7]
	_ = x[ErrCurrentSession-8]
}

const _Error_name = "ErrThemesErrActorsErrLockActorErrUnlockActorErrIsActorLockedErrResetActorLocksErrStartSessionErrStopSessionErrCurrentSession"

var _Error_index = [...]uint8{0, 9, 18, 30, 44, 60, 78, 93, 107, 124}

func (i Error) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Error_index)-1 {
		return "Error(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Error_name[_Error_index[idx]:_Error_index[idx+1]]
}
