// Code generated by "stringer -type=errSys"; DO NOT EDIT.

package https

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errUnknown-0]
	_ = x[errGetThemes-1]
	_ = x[errRepoThemes-2]
	_ = x[errGetActors-3]
	_ = x[errRepoActors-4]
	_ = x[errJsonEncode-5]
	_ = x[errJsonDecode-6]
	_ = x[errDecodeTxPayload-7]
	_ = x[errExpectedContentTypeJSON-8]
	_ = x[errBadRequest-9]
	_ = x[errStrconvSession-10]
	_ = x[errMax-11]
}

const _errSys_name = "errUnknownerrGetThemeserrRepoThemeserrGetActorserrRepoActorserrJsonEncodeerrJsonDecodeerrDecodeTxPayloaderrExpectedContentTypeJSONerrBadRequesterrStrconvSessionerrMax"

var _errSys_index = [...]uint8{0, 10, 22, 35, 47, 60, 73, 86, 104, 130, 143, 160, 166}

func (i errSys) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_errSys_index)-1 {
		return "errSys(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _errSys_name[_errSys_index[idx]:_errSys_index[idx+1]]
}
