// Code generated by "stringer -type=errSys"; DO NOT EDIT.

package https

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errUnknown-0]
	_ = x[errGetThemes-1]
	_ = x[errRepoThemes-2]
	_ = x[errJsonEncode-3]
	_ = x[errMax-4]
}

const _errSys_name = "errUnknownerrGetThemeserrRepoThemeserrJsonEncodeerrMax"

var _errSys_index = [...]uint8{0, 10, 22, 35, 48, 54}

func (i errSys) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_errSys_index)-1 {
		return "errSys(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _errSys_name[_errSys_index[idx]:_errSys_index[idx+1]]
}
