// Code generated by "stringer -type=errDecode"; DO NOT EDIT.

package wss

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errNilBody-0]
	_ = x[errNilBodyJoin-1]
	_ = x[errNilBodyThemeLock-2]
	_ = x[errNilBodyActorLock-3]
	_ = x[errNilSocket-4]
	_ = x[errSocketClosed-5]
	_ = x[errConnWriter-6]
	_ = x[errCloseConnWriter-7]
	_ = x[errCipher-8]
	_ = x[errJsonEncode-9]
	_ = x[errAgeEncrypt-10]
	_ = x[errAgeDecrypt-11]
	_ = x[errCloseAgeEncrypt-12]
	_ = x[errCloseBase64Encoder-13]
	_ = x[errCopyBase64-14]
}

const _errDecode_name = "errNilBodyerrNilBodyJoinerrNilBodyThemeLockerrNilBodyActorLockerrNilSocketerrSocketClosederrConnWritererrCloseConnWritererrCiphererrJsonEncodeerrAgeEncrypterrAgeDecrypterrCloseAgeEncrypterrCloseBase64EncodererrCopyBase64"

var _errDecode_index = [...]uint8{0, 10, 24, 43, 62, 74, 89, 102, 120, 129, 142, 155, 168, 186, 207, 220}

func (i errDecode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_errDecode_index)-1 {
		return "errDecode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _errDecode_name[_errDecode_index[idx]:_errDecode_index[idx+1]]
}
