// Code generated by "stringer -type=eventType"; DO NOT EDIT.

package wss

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[eventError-0]
	_ = x[eventJoin-1]
	_ = x[eventKeyBroadcast-2]
	_ = x[eventThemeLock-3]
	_ = x[eventActorLock-4]
	_ = x[eventUnknown-5]
}

const _eventType_name = "eventErroreventJoineventKeyBroadcasteventThemeLockeventActorLockeventUnknown"

var _eventType_index = [...]uint8{0, 10, 19, 36, 50, 64, 76}

func (i eventType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_eventType_index)-1 {
		return "eventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _eventType_name[_eventType_index[idx]:_eventType_index[idx+1]]
}
