// Code generated by "stringer -type=errAdapter"; DO NOT EDIT.

package sqlite

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errZero-0]
	_ = x[errOpenDB-1]
	_ = x[errUnknown-2]
}

const _errAdapter_name = "errZeroerrOpenDBerrUnknown"

var _errAdapter_index = [...]uint8{0, 7, 16, 26}

func (i errAdapter) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_errAdapter_index)-1 {
		return "errAdapter(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _errAdapter_name[_errAdapter_index[idx]:_errAdapter_index[idx+1]]
}
