// Code generated by "stringer -type=errAdapter"; DO NOT EDIT.

package sqlite

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errZero-0]
	_ = x[errOpenDB-1]
	_ = x[errSelectThemes-2]
	_ = x[errSelectThemesIter-3]
	_ = x[errSelectThemesScan-4]
	_ = x[errSelectActors-5]
	_ = x[errSelectActorsIter-6]
	_ = x[errSelectActorsScan-7]
	_ = x[errUnknown-8]
}

const _errAdapter_name = "errZeroerrOpenDBerrSelectThemeserrSelectThemesItererrSelectThemesScanerrSelectActorserrSelectActorsItererrSelectActorsScanerrUnknown"

var _errAdapter_index = [...]uint8{0, 7, 16, 31, 50, 69, 84, 103, 122, 132}

func (i errAdapter) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_errAdapter_index)-1 {
		return "errAdapter(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _errAdapter_name[_errAdapter_index[idx]:_errAdapter_index[idx+1]]
}
